version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WeddingInvitationSystem
    ports:
      - "5433:5432"  # Maps local port 5433 to container port 5432
    networks:
      - spring-boot-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 515966542061.dkr.ecr.us-east-1.amazonaws.com/spring-boot-app:latest
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/WeddingInvitationSystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8081:8080"  # Maps local port 8081 to container port 8080
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge
